### IndieKit configuration for Hugo micro-blog (notes)
plugins:
  - '@indiekit/store-file-system'
  - '@indiekit/preset-hugo'
  - '@indiekit/endpoint-auth'
  - '@indiekit/endpoint-files'
  - '@indiekit/endpoint-image'
  - '@indiekit/endpoint-media'
  - '@indiekit/endpoint-micropub'
  - '@indiekit/endpoint-posts'
  - '@indiekit/endpoint-share'
  - '@indiekit/endpoint-syndicate'
  - '@indiekit/post-type-article'
  - '@indiekit/post-type-bookmark'
  - '@indiekit/post-type-like'
  - '@indiekit/post-type-note'
  - '@indiekit/post-type-photo'
  - '@indiekit/post-type-reply'

# Configure the file system store to write to the project root
'@indiekit/store-file-system':
  directory: .

# Use default front-matter format (YAML) for Hugo preset
'@indiekit/preset-hugo':
  frontMatterFormat: yaml