### IndieKit configuration for Hugo micro-blog (notes)
publication:
  me: "https://vghpe.github.io/blog/"
  # base URL of your Hugo site, used for building post URLs
 # plugins list below
# Core plugins for file-based Micropub → Hugo notes
plugins:
  - '@indiekit/store-file-system'
  - '@indiekit/preset-hugo'
  - '@indiekit/endpoint-auth'
  - '@indiekit/endpoint-micropub'
  - '@indiekit/post-type-note'

# Configure the file system store to write to the project root
'@indiekit/store-file-system':
  directory: .

# Use default front-matter format (YAML) for Hugo preset
'@indiekit/preset-hugo':
  frontMatterFormat: yaml