baseURL = "https://vghpe.github.io/blog/"
title = "vghpe - R&D"
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
theme = 'mini'
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
[params]
hiddenPostSummaryInHomePage = false
enableRSS = true
subscribe = "RSS"
copyright = "© 2024 Henrik Pettersson. All rights reserved."
showPowerBy = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 2
