baseURL = "https://vghpe.github.io/blog/"
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
theme = 'mini'
[params]
hiddenPostSummaryInHomePage = false 


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
